# @package _global_
# RedCaps Dataset Configuration

# Dataset paths
data:
  dataset_type: "redcaps"
  train_annotation_path: "/data/PDD/redcaps/redcaps_plus/redcaps_medium.json"
  test_annotation_path: "/local/wding/Dataset/coco/annotations/coco_karpathy_test.json"
  train_image_path: ""
  test_image_path: "/local/wding/Dataset/coco/images"

# Feature manager paths - dataset specific
featuremanager:
  storage_dir: "/local/wding/pre_extract/redcaps/features"
  sample_ids_path: "/local/wding/pre_extract/redcaps/sample_ids.pt"

# Experiment Configuration
experiment:
  name: "CoSiR_Experiment"
  tags: ["CoSiR", "RedCaps", "Cluster"]
  description: "Comprehensive experiment for CoSiR"
  results_dir: "res/CoSiR_Experiment/redcaps" # Depends on the dataset

# This is for redcaps test set
# test_annotation_path: "/data/PDD/redcaps/redcaps_plus/redcaps_test.json"
# test_image_path: "/data/PDD"
