#!/usr/bin/env python3
"""Create PercepT Stage-1 embedding and label-composition diagnostics.

This standalone script uses the deterministic embedding snapshot generated by the
Stage-1 pilot.  It writes the two report figures alongside this file's diagrams.
"""

from __future__ import annotations

from pathlib import Path

import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from matplotlib.patches import Rectangle
import numpy as np
from sklearn.manifold import TSNE


SNAPSHOT_PATH = Path("/project/CoSiR/res/percept/percept_stage1_embedding_snapshot.npz")
OUTPUT_DIR = Path(__file__).resolve().parent / "diagrams"
EMBEDDING_OUTPUT = OUTPUT_DIR / "percept_stage1_embedding_before_after_tsne.png"
COMPOSITION_OUTPUT = OUTPUT_DIR / "percept_stage1_cluster_label_composition.png"
LABEL_COMPOSITION_BEFORE_AFTER_OUTPUT = OUTPUT_DIR / "percept_stage1_label_composition_before_after.png"

RANDOM_SEED = 42
MAX_TSNE_POINTS = 6_000
N_TOPICS = 40
N_INITIAL_CLUSTERS = 60

BLACK = "#1A1A1A"
GRAY = "#595959"
LIGHT_GRAY = "#E8E8E8"
BORDER = "#BFBFBF"
BLUE = "#1F77B4"
ORANGE = "#FF7F0E"
RED = "#C03030"
WHITE = "#FFFFFF"


def categorical_colormap() -> ListedColormap:
    """Return 60 distinct qualitative colors from Matplotlib's tab palettes."""
    colors = np.vstack([
        plt.get_cmap("tab20")(np.arange(20)),
        plt.get_cmap("tab20b")(np.arange(20)),
        plt.get_cmap("tab20c")(np.arange(20)),
    ])
    return ListedColormap(colors, name="percept_tab60")


def validate_snapshot(data: np.lib.npyio.NpzFile) -> None:
    """Fail early with a useful error if the diagnostic snapshot is incomplete."""
    expected = {
        "train_latent_pre", "train_latent_post", "train_initial_label", "train_topic",
        "train_emotion", "train_genre", "heldout_latent_pre", "heldout_latent_post",
        "heldout_topic", "heldout_emotion", "heldout_genre",
    }
    missing = sorted(expected.difference(data.files))
    if missing:
        raise ValueError(f"Snapshot is missing required arrays: {', '.join(missing)}")
    if data["train_latent_pre"].shape[1] != 128 or data["heldout_latent_pre"].shape[1] != 128:
        raise ValueError("Expected 128-D latent arrays in the snapshot.")
    if not np.all((data["train_topic"] >= 0) & (data["train_topic"] < N_TOPICS)):
        raise ValueError("Train topics must be integer ids in [0, 39].")
    if not np.all((data["heldout_topic"] >= 0) & (data["heldout_topic"] < N_TOPICS)):
        raise ValueError("Held-out topics must be integer ids in [0, 39].")


def subsample(latent: np.ndarray, labels: np.ndarray, rng: np.random.Generator) -> tuple[np.ndarray, np.ndarray, int]:
    """Sample at most MAX_TSNE_POINTS observations without replacement."""
    source_n = len(latent)
    if source_n <= MAX_TSNE_POINTS:
        return latent, labels, source_n
    indices = rng.choice(source_n, size=MAX_TSNE_POINTS, replace=False)
    return latent[indices], labels[indices], source_n


def tsne_2d(latent: np.ndarray) -> np.ndarray:
    """Run a deterministic, practical 2-D t-SNE projection for one panel."""
    perplexity = min(30, max(5, (len(latent) - 1) // 3))
    return TSNE(
        n_components=2,
        perplexity=perplexity,
        init="pca",
        random_state=RANDOM_SEED,
    ).fit_transform(latent)


def style_scatter_axis(axis: plt.Axes) -> None:
    axis.set_facecolor(WHITE)
    axis.grid(False)
    axis.tick_params(axis="both", which="both", length=2.5, color=BORDER,
                     labelbottom=False, labelleft=False)
    for spine in axis.spines.values():
        spine.set_color(BORDER)
        spine.set_linewidth(0.7)


def make_embedding_figure(data: np.lib.npyio.NpzFile) -> list[dict[str, int | str]]:
    """Write the Figure-3-style before/after t-SNE grid and return panel metadata."""
    cmap = categorical_colormap()
    rng = np.random.default_rng(RANDOM_SEED)
    # Panels are deliberately independently subsampled: each projection answers a
    # separate pre/post question, rather than claiming point-wise t-SNE alignment.
    panels = [
        ("Train, pre-DEC (K-means init, 60 clusters)", data["train_latent_pre"], data["train_initial_label"], N_INITIAL_CLUSTERS),
        ("Train, post-DEC (40 surviving topics)", data["train_latent_post"], data["train_topic"], N_TOPICS),
        ("Held-out, pre-DEC (colored by final topic, for reference)", data["heldout_latent_pre"], data["heldout_topic"], N_TOPICS),
        ("Held-out, post-DEC (40 surviving topics)", data["heldout_latent_post"], data["heldout_topic"], N_TOPICS),
    ]
    fig, axes = plt.subplots(2, 2, figsize=(14, 12), facecolor=WHITE)
    metadata: list[dict[str, int | str]] = []

    for axis, (title, latent, labels, expected_clusters) in zip(axes.flat, panels):
        sampled_latent, sampled_labels, source_n = subsample(latent, labels, rng)
        projection = tsne_2d(sampled_latent)
        axis.scatter(
            projection[:, 0], projection[:, 1], c=sampled_labels, cmap=cmap,
            vmin=0, vmax=59, s=2.5, alpha=0.62, linewidths=0, rasterized=True,
        )
        style_scatter_axis(axis)
        axis.set_title(title, color=BLACK, fontsize=11, fontweight="bold", pad=10)
        shown_clusters = len(np.unique(sampled_labels))
        sample_note = f"{shown_clusters} clusters, n={len(sampled_latent):,}"
        if len(sampled_latent) < source_n:
            sample_note += f" (subsampled from {source_n:,})"
        axis.text(0.5, -0.12, sample_note, transform=axis.transAxes, ha="center",
                  va="top", color=GRAY, fontsize=9)
        metadata.append({"title": title, "plotted": len(sampled_latent), "source": source_n,
                         "expected_clusters": expected_clusters, "shown_clusters": shown_clusters})

    fig.suptitle(
        "PercepT Stage 1: embedding space before vs. after DEC (K=60/40, seed 42)",
        color=BLACK, fontsize=16, fontweight="bold", y=0.98,
    )
    fig.subplots_adjust(left=0.055, right=0.985, top=0.925, bottom=0.075, hspace=0.31, wspace=0.14)
    fig.savefig(EMBEDDING_OUTPUT, dpi=300, facecolor=WHITE)
    plt.close(fig)
    return metadata


def composition_matrix(topics: np.ndarray, labels: np.ndarray, categories: list[str]) -> tuple[np.ndarray, np.ndarray]:
    """Build a topic-by-label count matrix and its row-normalized version."""
    counts = np.zeros((N_TOPICS, len(categories)), dtype=int)
    category_index = {category: index for index, category in enumerate(categories)}
    for topic, label in zip(topics.astype(int), labels.astype(str)):
        counts[topic, category_index[label]] += 1
    totals = counts.sum(axis=1)
    fractions = np.divide(counts, totals[:, None], out=np.full_like(counts, np.nan, dtype=float), where=totals[:, None] != 0)
    return fractions, totals


def style_heatmap_axis(axis: plt.Axes, categories: list[str]) -> None:
    axis.set_xticks(np.arange(len(categories)), categories, rotation=30, ha="right", fontsize=8, color=BLACK)
    axis.set_yticks(np.arange(N_TOPICS), [str(topic) for topic in range(N_TOPICS)], fontsize=6.5, color=BLACK)
    axis.set_ylabel("DEC topic id", color=BLACK, fontsize=9)
    axis.tick_params(length=0)
    for spine in axis.spines.values():
        spine.set_color(BORDER)
        spine.set_linewidth(0.7)


def draw_composition_panel(axis: plt.Axes, fractions: np.ndarray, totals: np.ndarray,
                           categories: list[str], title: str, hatch_empty: bool) -> plt.AxesImage:
    """Draw a 40-row composition heatmap plus an aligned row-count margin."""
    masked = np.ma.masked_invalid(fractions)
    cmap = plt.get_cmap("Blues").copy()
    cmap.set_bad(WHITE)
    image = axis.imshow(masked, interpolation="nearest", aspect="auto", cmap=cmap, vmin=0, vmax=1)
    style_heatmap_axis(axis, categories)
    axis.set_title(title, color=BLACK, fontsize=11, fontweight="bold", loc="left", pad=10)
    for topic in np.flatnonzero(totals == 0):
        if hatch_empty:
            axis.add_patch(Rectangle((-0.5, topic - 0.5), len(categories), 1, facecolor="none",
                                     edgecolor=BORDER, hatch="////", linewidth=0.0))
    count_axis = axis.twinx()
    count_axis.set_ylim(axis.get_ylim())
    count_axis.set_yticks(np.arange(N_TOPICS), [f"{count:,}" for count in totals], fontsize=6.5, color=GRAY)
    count_axis.tick_params(axis="y", length=0, pad=4)
    count_axis.set_ylabel("row n", rotation=270, labelpad=13, color=GRAY, fontsize=8)
    for spine in count_axis.spines.values():
        spine.set_visible(False)
    return image


def make_composition_figure(data: np.lib.npyio.NpzFile) -> tuple[list[int], int, int]:
    """Write the Figure-5-style held-out emotion and train genre heatmaps."""
    emotion_categories = sorted(np.unique(data["heldout_emotion"].astype(str)).tolist())
    train_genre = data["train_genre"].astype(str)
    genre_categories = sorted(np.unique(train_genre[train_genre != ""]).tolist())
    if len(emotion_categories) != 9 or len(genre_categories) != 9:
        raise ValueError(f"Expected 9 emotion and 9 genre categories, got {len(emotion_categories)} and {len(genre_categories)}.")

    emotion_fractions, emotion_totals = composition_matrix(
        data["heldout_topic"], data["heldout_emotion"], emotion_categories,
    )
    genre_mask = train_genre != ""
    genre_fractions, genre_totals = composition_matrix(
        data["train_topic"][genre_mask], train_genre[genre_mask], genre_categories,
    )
    zero_genre_topics = np.flatnonzero(genre_totals == 0).astype(int).tolist()

    fig, axes = plt.subplots(2, 1, figsize=(14, 16), facecolor=WHITE)
    image = draw_composition_panel(
        axes[0], emotion_fractions, emotion_totals, emotion_categories,
        "Held-out emotion composition per topic (n=9,365, full coverage)", hatch_empty=False,
    )
    draw_composition_panel(
        axes[1], genre_fractions, genre_totals, genre_categories,
        "Train genre composition per topic (n=1,144 genre-labelled paintings out of 61,402 -- sparse, read per-row n)",
        hatch_empty=True,
    )
    colorbar = fig.colorbar(image, ax=axes, location="right", fraction=0.025, pad=0.08)
    colorbar.set_label("fraction of topic members", color=GRAY, fontsize=9)
    colorbar.ax.tick_params(labelsize=8, colors=GRAY)
    colorbar.outline.set_edgecolor(BORDER)
    fig.suptitle(
        "PercepT Stage 1 (K=60/40): does each cluster correspond to a coherent label mixture?",
        color=BLACK, fontsize=15, fontweight="bold", y=0.985,
    )
    fig.text(
        0.5, 0.018,
        "Genre coverage is far sparser than emotion coverage in this dataset; interpret per-topic genre rows with very small n cautiously.",
        ha="center", va="bottom", color=GRAY, fontsize=9,
    )
    fig.subplots_adjust(left=0.16, right=0.83, top=0.94, bottom=0.065, hspace=0.32)
    fig.savefig(COMPOSITION_OUTPUT, dpi=300, facecolor=WHITE)
    plt.close(fig)
    return zero_genre_topics, int(emotion_totals.sum()), int(genre_totals.sum())


def comparison_composition_matrix(assignments: np.ndarray, labels: np.ndarray,
                                  categories: list[str], n_rows: int) -> tuple[np.ndarray, np.ndarray]:
    """Build a row-normalized cluster/topic composition matrix for a chosen assignment."""
    counts = np.zeros((n_rows, len(categories)), dtype=int)
    category_index = {category: index for index, category in enumerate(categories)}
    for assignment, label in zip(assignments.astype(int), labels.astype(str)):
        counts[assignment, category_index[label]] += 1
    totals = counts.sum(axis=1)
    fractions = np.divide(
        counts, totals[:, None], out=np.full_like(counts, np.nan, dtype=float),
        where=totals[:, None] != 0,
    )
    return fractions, totals


def weighted_purity(assignments: np.ndarray, labels: np.ndarray,
                    categories: list[str], n_rows: int) -> float:
    """Return member-weighted max-label purity over non-empty assignment rows."""
    fractions, totals = comparison_composition_matrix(assignments, labels, categories, n_rows)
    top_counts = np.nan_to_num(fractions, nan=0.0).max(axis=1) * totals
    return float(top_counts.sum() / totals.sum())


def draw_comparison_composition_panel(axis: plt.Axes, fractions: np.ndarray, totals: np.ndarray,
                                      categories: list[str], title: str, row_label: str,
                                      hatch_empty: bool) -> plt.AxesImage:
    """Draw one variable-height before/after composition heatmap with row counts."""
    n_rows = len(totals)
    masked = np.ma.masked_invalid(fractions)
    cmap = plt.get_cmap("Blues").copy()
    cmap.set_bad(WHITE)
    image = axis.imshow(masked, interpolation="nearest", aspect="auto", cmap=cmap, vmin=0, vmax=1)
    axis.set_xticks(np.arange(len(categories)), categories, rotation=30, ha="right", fontsize=8, color=BLACK)
    axis.set_yticks(np.arange(n_rows), [str(row) for row in range(n_rows)], fontsize=5.4, color=BLACK)
    axis.set_ylabel(row_label, color=BLACK, fontsize=9)
    axis.tick_params(length=0)
    for spine in axis.spines.values():
        spine.set_color(BORDER)
        spine.set_linewidth(0.7)
    axis.set_title(title, color=BLACK, fontsize=11, fontweight="bold", loc="left", pad=10)
    if hatch_empty:
        for row in np.flatnonzero(totals == 0):
            axis.add_patch(Rectangle((-0.5, row - 0.5), len(categories), 1, facecolor="none",
                                     edgecolor=BORDER, hatch="////", linewidth=0.0))
    count_axis = axis.twinx()
    count_axis.set_ylim(axis.get_ylim())
    count_axis.set_yticks(np.arange(n_rows), [f"{count:,}" for count in totals], fontsize=5.4, color=GRAY)
    count_axis.tick_params(axis="y", length=0, pad=4)
    count_axis.set_ylabel("row n", rotation=270, labelpad=13, color=GRAY, fontsize=8)
    for spine in count_axis.spines.values():
        spine.set_visible(False)
    return image


def make_label_composition_before_after_figure(data: np.lib.npyio.NpzFile) -> dict[str, float | int | list[int]]:
    """Write train-only pre-/post-DEC label-composition heatmaps and purity metadata."""
    train_emotion = data["train_emotion"].astype(str)
    train_genre = data["train_genre"].astype(str)
    initial_labels = data["train_initial_label"]
    topic_labels = data["train_topic"]
    emotion_categories = sorted(np.unique(train_emotion).tolist())
    genre_mask = train_genre != ""
    genre_categories = sorted(np.unique(train_genre[genre_mask]).tolist())
    if len(emotion_categories) != 9 or len(genre_categories) != 9:
        raise ValueError(f"Expected 9 emotion and 9 genre categories, got {len(emotion_categories)} and {len(genre_categories)}.")

    emotion_pre, emotion_pre_totals = comparison_composition_matrix(
        initial_labels, train_emotion, emotion_categories, N_INITIAL_CLUSTERS,
    )
    emotion_post, emotion_post_totals = comparison_composition_matrix(
        topic_labels, train_emotion, emotion_categories, N_TOPICS,
    )
    genre_pre, genre_pre_totals = comparison_composition_matrix(
        initial_labels[genre_mask], train_genre[genre_mask], genre_categories, N_INITIAL_CLUSTERS,
    )
    genre_post, genre_post_totals = comparison_composition_matrix(
        topic_labels[genre_mask], train_genre[genre_mask], genre_categories, N_TOPICS,
    )
    emotion_pre_purity = weighted_purity(initial_labels, train_emotion, emotion_categories, N_INITIAL_CLUSTERS)
    emotion_post_purity = weighted_purity(topic_labels, train_emotion, emotion_categories, N_TOPICS)
    genre_pre_purity = weighted_purity(
        initial_labels[genre_mask], train_genre[genre_mask], genre_categories, N_INITIAL_CLUSTERS,
    )
    genre_post_purity = weighted_purity(
        topic_labels[genre_mask], train_genre[genre_mask], genre_categories, N_TOPICS,
    )

    fig, axes = plt.subplots(2, 2, figsize=(18, 19), facecolor=WHITE)
    emotion_image = draw_comparison_composition_panel(
        axes[0, 0], emotion_pre, emotion_pre_totals, emotion_categories,
        "Emotion, pre-DEC (60 K-means clusters)", "K-means cluster id", hatch_empty=False,
    )
    draw_comparison_composition_panel(
        axes[0, 1], emotion_post, emotion_post_totals, emotion_categories,
        "Emotion, post-DEC (40 DEC topics)", "DEC topic id", hatch_empty=False,
    )
    genre_image = draw_comparison_composition_panel(
        axes[1, 0], genre_pre, genre_pre_totals, genre_categories,
        "Genre, pre-DEC (60 K-means clusters)", "K-means cluster id", hatch_empty=True,
    )
    draw_comparison_composition_panel(
        axes[1, 1], genre_post, genre_post_totals, genre_categories,
        "Genre, post-DEC (40 DEC topics)", "DEC topic id", hatch_empty=True,
    )
    for image, row_axes in ((emotion_image, axes[0, :]), (genre_image, axes[1, :])):
        colorbar = fig.colorbar(image, ax=row_axes, location="right", fraction=0.025, pad=0.08)
        colorbar.set_label("fraction of row members", color=GRAY, fontsize=9)
        colorbar.ax.tick_params(labelsize=8, colors=GRAY)
        colorbar.outline.set_edgecolor(BORDER)
    fig.suptitle(
        "PercepT Stage 1: does DEC change label-cluster alignment vs. plain K-means? (train split)",
        color=BLACK, fontsize=15, fontweight="bold", y=0.985,
    )
    genre_n = int(genre_mask.sum())
    fig.text(
        0.5, 0.018,
        f"Weighted-average per-cluster purity: emotion {emotion_pre_purity:.4f} (60 clusters) -> "
        f"{emotion_post_purity:.4f} (40 topics); genre {genre_pre_purity:.4f} (60 clusters) -> "
        f"{genre_post_purity:.4f} (40 topics), n={genre_n:,}. Raw purity is not directly comparable across "
        "different cluster counts -- fewer, larger clusters mechanically tend to show LOWER max-label purity "
        "than more, smaller clusters, independent of any real change in label alignment. This is why this "
        "investigation uses chance-corrected Adjusted Mutual Information (AMI), not raw purity, as its primary "
        "metric elsewhere: for this exact fit, held-out emotion AMI=0.1225 and held-out genre AMI=0.2274 "
        "(both already reported). The side-by-side heatmaps above are for qualitative visual comparison of "
        "which labels dominate which clusters, not for reading a purity number as a win/loss verdict.",
        ha="center", va="bottom", color=GRAY, fontsize=8, wrap=True,
    )
    fig.subplots_adjust(left=0.09, right=0.84, top=0.94, bottom=0.16, hspace=0.31, wspace=0.62)
    fig.savefig(LABEL_COMPOSITION_BEFORE_AFTER_OUTPUT, dpi=300, facecolor=WHITE)
    plt.close(fig)
    return {
        "emotion_pre_purity": emotion_pre_purity,
        "emotion_post_purity": emotion_post_purity,
        "genre_pre_purity": genre_pre_purity,
        "genre_post_purity": genre_post_purity,
        "emotion_n": int(emotion_pre_totals.sum()),
        "genre_n": genre_n,
        "zero_genre_initial_clusters": np.flatnonzero(genre_pre_totals == 0).astype(int).tolist(),
        "zero_genre_topics": np.flatnonzero(genre_post_totals == 0).astype(int).tolist(),
    }


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    if not SNAPSHOT_PATH.is_file():
        raise FileNotFoundError(f"Embedding snapshot not found: {SNAPSHOT_PATH}")
    with np.load(SNAPSHOT_PATH, allow_pickle=True) as data:
        validate_snapshot(data)
        panel_metadata = make_embedding_figure(data)
        zero_genre_topics, emotion_n, genre_n = make_composition_figure(data)
        comparison = make_label_composition_before_after_figure(data)

    print("Generated files:")
    for path in (EMBEDDING_OUTPUT, COMPOSITION_OUTPUT, LABEL_COMPOSITION_BEFORE_AFTER_OUTPUT):
        print(f"  {path}: exists={path.is_file()}, bytes={path.stat().st_size if path.is_file() else 0:,}")
    print("t-SNE panel sample sizes:")
    for panel in panel_metadata:
        print(f"  {panel['title']}: n={panel['plotted']:,} (source n={panel['source']:,})")
    print(f"Composition coverage: held-out emotion n={emotion_n:,}; train genre-labelled n={genre_n:,}")
    print(f"Topics with zero train genre-labelled members: {zero_genre_topics}")
    print("Train-only before/after weighted purities: "
          f"emotion {comparison['emotion_pre_purity']:.4f} -> {comparison['emotion_post_purity']:.4f}; "
          f"genre {comparison['genre_pre_purity']:.4f} -> {comparison['genre_post_purity']:.4f}")
    print(f"Pre-DEC clusters with zero genre-labelled members: {comparison['zero_genre_initial_clusters']}")
    print(f"Post-DEC topics with zero genre-labelled members: {comparison['zero_genre_topics']}")
    print("Warnings/errors: none.")


if __name__ == "__main__":
    main()
