# CoSiR Training Configuration
defaults:
  - _self_

# Random seed for reproducibility
seed: 42

# Device configuration
device: cuda

# General training configuration
train:
  epochs: 20
  lr: 1.0e-6
  weight_decay: 5.0e-2
  num_workers: 4
  batch_size: 256
  initialization_strategy: imgtxt
  load_existing_features: true
  evaluation_interval: 5
  representative_number: 10

# Model configuration
model:
  embedding_dim: 2
  clip_model: "openai/clip-vit-base-patch32"
  freeze_backbone: true

# Feature manager configuration
featuremanager:
  storage_dir: "/project/CoSiR/data/comprehensive_cosir_test/features"
  sample_ids_path: "/project/CoSiR/data/comprehensive_cosir_test/sample_ids.pt"
  primary_backend: "chunked"
  chunk_size: 1024
  cache_size_mb: 512
  use_compression: false
  chunked_storage:
    enabled: true
    compression: false
  cache:
    l1_size_mb: 512
    l2_size_mb: 1024
    l3_path: null

# Embedding manager configuration
embeddingmanager:
  storage_mode: "disk"
  initialization_strategy: "zeros"
  cache_l1_size_mb: 128
  cache_l2_size_mb: 256
  enable_l3_cache: true
  auto_sync: false
  sync_batch_size: 10
  embedding_chunk_size: null  # Auto-optimize based on batch_size
  enable_performance_monitoring: true
  log_cache_stats_every_n_epochs: 5
  force_sync_at_epoch_end: true

# Loss function configuration
loss:
  margin: 0.3
  lambda_pos: 1.0
  lambda_neg: 1.0
  lambda_labelchange: 0.1
  lambda_preserve: 0.1
  return_dict: true

# Optimizer configuration
optimizer:
  type: "AdamW"
  lr: 1.0e-6
  weight_decay: 5.0e-2
  label_lr_multiplier: 5.0e4  # Label embedding learning rate multiplier

# Scheduler configuration
scheduler:
  type: "CosineAnnealingLR"
  T_max: 20  # Should match train.epochs
  eta_min: 1.0e-9

# Dataset paths
data:
  train_annotation_path: "/data/SSD/coco/annotations/coco_karpathy_train.json"
  test_annotation_path: "/data/SSD/coco/annotations/coco_karpathy_test.json"
  train_image_path: "/data/SSD/coco/images"
  test_image_path: "/data/SSD/coco/images"

# Evaluation configuration
eval:
  k_vals: [1, 5, 10]
  train_max_batches: 20  # Should match train.epochs
  print_metrics: true
  evaluation_interval: 5

# Experiment configuration
experiment:
  name: "comprehensive_cosir_test"
  tags: ["deep_clustering", "multimodal", "comprehensive_test"]
  description: "Comprehensive test of integrated feature and experiment management systems"
  results_dir: "res/comprehensive_cosir_test/experiments"

# W&B logging configuration
wandb:
  enabled: true
  project: cosir
  entity: augustoxq
  name: ""
  tags: [Local]
  notes: "CoSiR训练"
  mode: online