# @package _global_
# Training Configuration

train:
  epochs: 15
  num_workers: 0
  batch_size: 1024 # This is the batchsize of the evaluation set
  load_existing_features: True
  representative_number: 36 # This should equal to selected number of conditions * number of grids
  initialization_scale: 1.0
  initialization_method: svd

# Loss function configuration
loss:
  temperature: 0.07
  lambda_margin: 1.0
  lambda_infonce: 0.3
  lambda_diversity: 0.1
  lambda_preserve: 0.1
  return_dict: true

# Optimizer configuration
optimizer:
  type: "AdamW"
  lr: 1.0e-5
  weight_decay: 5.0e-2

# Scheduler configuration
scheduler:
  type: "CosineAnnealingLR"
  T_max: 0 # Should match train.epochs
  eta_min: 1.0e-9

# Evaluation configuration
eval:
  k_vals: [1, 5, 10]
  train_max_batches: 25 # This is during validation, how many batches we check
  print_metrics: true
  evaluation_interval: 3
  perform_evaluation: true
